[phases.setup]
nixPkgs = ["dotnet-sdk_8.0"]

[phases.build]
cmds = ["dotnet restore", "dotnet publish -c Release -o /app/publish --no-restore"]

[phases.start]
cmd = "dotnet /app/publish/WSSubscription.dll"